version: '3.9'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: on-failure
    env_file: ./.env
    ports:
      - 3001:3001
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=digital_wallet
    networks:
      - wallet-net
    depends_on:
      - postgres
    stdin_open: true
    tty: true
  postgres:
    image: postgres:14
    restart: always
    env_file: ./.env
    environment:
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_USER=$DB_USER
      - POSTGRES_DB=digital_wallet
    networks:
      - wallet-net
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
networks:
  wallet-net:
     driver: bridge
volumes:
  db: