version: '3.9'
services:
  frontend:
    image: humbertobonadiman/digital-wallet-frontend:1.0.0
    build: ./frontend
    ports: 
      - 3000:3000
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3000"]  # Caso utilize outra porta interna para o front, altere ela aqui também
      timeout: 10s
      retries: 5
  backend:
    image: humbertobonadiman/digital-wallet-backend:1.0.0
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: on-failure
    ports:
      - 3001:3001
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=digital_wallet
    networks:
      - wallet-net
    depends_on:
      - postgres
    stdin_open: true
    tty: true
  postgres:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_USER=$DB_USER
      - POSTGRES_DB=digital_wallet
    networks:
      - wallet-net
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
networks:
  wallet-net:
     driver: bridge
volumes:
  db:
