name: Continuos Integration with GitHub

on:

  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: 'Create env file in root directory'
        run: |
          echo "${{ secrets.ENV_ROOT }}" > .env
      - uses: actions/checkout@v3
      
      - name: 'Create env file in backend directory'
        run: |
          echo "${{ secrets.ENV_BACKEND }}" > .env
      - uses: actions/checkout@v3

      - name: Docker Login
        uses: docker/login-action@v2.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.5.1
        with:
          node-version: v.16.18.1
          token: npm
          cache: package-lock.json
