name: Continuos Integration with GitHub

on:

  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: 'Create env file in root directory'
        run: |
          echo "${{ secrets.ENV_ROOT }}" > .env
      - uses: actions/checkout@v3
      
      - name: 'Create env file in backend directory'
        run: |
          echo "${{ secrets.ENV_BACKEND }}" > .env
      - uses: actions/checkout@v3

      - name: Docker Login
        uses: docker/login-action@v2.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.5.1
        with:
          node-version: v16.18.1
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            docker tag ${{ secrets.DOCKER_USERNAME }}/digital-wallet-frontend:1.0.0 ${{ secrets.DOCKER_USERNAME }}/digital-wallet-frontend:${{github.run_id}}
            docker tag ${{ secrets.DOCKER_USERNAME }}/digital-wallet-frontend:1.0.0 ${{ secrets.DOCKER_USERNAME }}/digital-wallet-frontend:latest
            docker tag ${{ secrets.DOCKER_USERNAME }}/digital-wallet-backend:1.0.0 ${{ secrets.DOCKER_USERNAME }}/digital-wallet-backend:${{github.run_id}}
            docker tag ${{ secrets.DOCKER_USERNAME }}/digital-wallet-backend:1.0.0 ${{ secrets.DOCKER_USERNAME }}/digital-wallet-backend:latest
            docker push ${{ secrets.DOCKER_USERNAME }}/digital-wallet-frontend:${{github.run_id}}
            docker push ${{ secrets.DOCKER_USERNAME }}/digital-wallet-frontend:latest
            docker push ${{ secrets.DOCKER_USERNAME }}/digital-wallet-backend:${{github.run_id}}
            docker push ${{ secrets.DOCKER_USERNAME }}/digital-wallet-backend:latest
          secrets: |
            "POSTGRES_USER=${{ secrets.POSTGRES_USER }}"
            "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}"

